'use client';
import { useMemo, useRef, useState } from 'react';
import { motion } from 'framer-motion';
import { CloudUpload, FileText, Loader2, Shield } from 'lucide-react';
import { SUPPORTED_EXTENSIONS } from '@/lib/constants';
import { formatBytes } from '@/lib/format';
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import { Card, CardBody } from '@/components/ui/card';
export function UploadDropzone({ file, onFile, loading }: { file: File | null; onFile: (file: File | null) => void; loading?: boolean }) { const inputRef = useRef<HTMLInputElement>(null); const [dragActive, setDragActive] = useState(false); const accept = useMemo(() => SUPPORTED_EXTENSIONS.join(','), []); return <Card className={cn('border-dashed transition', dragActive && 'border-yellow-400 bg-yellow-50')}><CardBody><motion.div animate={{ y: dragActive ? -2 : 0 }} className="flex flex-col items-center justify-center rounded-2xl border border-dashed border-zinc-200 bg-zinc-50 px-6 py-10 text-center" onDragOver={(e) => { e.preventDefault(); setDragActive(true); }} onDragLeave={() => setDragActive(false)} onDrop={(e) => { e.preventDefault(); setDragActive(false); const dropped = e.dataTransfer.files?.[0]; if (dropped) onFile(dropped); }}><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-yellow-100 text-zinc-900"><CloudUpload className="h-7 w-7" /></div><h3 className="mt-4 text-lg font-semibold text-zinc-900">Drop a contract file here</h3><p className="mt-2 max-w-xl text-sm leading-6 text-zinc-600">Upload PDF, DOCX, DOC, EML, MP3, WAV or M4A files. The backend will extract a canonical document and generate NDA or SOW outputs.</p><div className="mt-6 flex flex-wrap items-center justify-center gap-3"><Button type="button" variant="primary" onClick={() => inputRef.current?.click()} disabled={loading}>{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <FileText className="h-4 w-4" />}Choose file</Button><Button type="button" variant="secondary" onClick={() => onFile(null)}>Clear</Button></div><input ref={inputRef} type="file" accept={accept} className="hidden" onChange={(e) => onFile(e.target.files?.[0] ?? null)} /></motion.div>{file ? <div className="mt-4 flex items-center justify-between rounded-xl border border-zinc-200 bg-white px-4 py-3 text-sm"><div><p className="font-medium text-zinc-900">{file.name}</p><p className="text-zinc-500">{formatBytes(file.size)}</p></div><div className="flex items-center gap-2 rounded-full bg-yellow-100 px-3 py-1 text-xs font-medium text-zinc-900"><Shield className="h-3.5 w-3.5" />Ready to analyze</div></div> : null}</CardBody></Card>; }